examples/deepzoom: fix ./deepzoom_tile.py -r with jinja2 3.x
If our code was specified directly to Python (e.g. we're running as a
command-line script), rather than running from a module, PackageLoader in
jinja2 3.x fails to read our template with:

    ValueError: __main__.__spec__ is None

Read the template directly from the filesystem in this case.