Fix fallback _load_image() with Pillow 3.x
Fixes Pillow exception on image read when we're installed
--without-performance:

    Exception: tostring() has been removed. Please call tobytes() instead.

Found by @andrewmfiorillo.